function propagation_model = propagation_model_selector(prop_model)

if strcmp(prop_model.type{1},'raytracing')
    propagation_model = propagationModel(prop_model.type{1}, ...
        'Method',prop_model.ray_method, ...
        'MaxNumReflections',prop_model.max_reflections, ...
        'AngularSeparation',prop_model.angular_separation, ...
        'BuildingsMaterial',prop_model.buildings_material, ...
        'TerrainMaterial',prop_model.terrain_material);
elseif strcmp(prop_model.type{1},'longley-rice')
    propagation_model = propagationModel(prop_model.type{1});
end

if length(prop_model.type) > 1
    for i = 2:length(prop_model.type)
        if strcmp(prop_model.type{i},'rain')
            propagation_model = add(propagation_model,propagationModel(prop_model.type{i},...
                'RainRate',prop_model.rain_rate));
        elseif strcmp(prop_model.type{i},'gas')
            propagation_model = add(propagation_model,propagationModel(prop_model.type{i},...
                'Temperature',prop_model.temperature,...
                'AirPressure',prop_model.air_pressure,...
                'WaterDensity',prop_model.water_density));
        elseif strcmp(prop_model.type{i},'fog')
            propagation_model = add(propagation_model,propagationModel(prop_model.type{i},...
                'Temperature',prop_model.temperature,...
                'WaterDensity',prop_model.water_density));
        end
    end
end

end